### ISSUE TITLE
你的go.emoji/official/emoji-sequences.go有问题吧？范围标识变成只有2个？？

### ISSUE THREAD

**Issue by dilllay** [Andrew-M-C/go.emoji#1]
打比方unicode文档内的标识是：
1F191..1F19A  ; Basic_Emoji                  ; CL button                                                      # E0.6  [10] (🆑..🆚)

而你生成出来的只有2个，实际上源文档内这里有10个符号：
        AllSequences.AddSequence([]rune{0x1f191}, "Basic_Emoji                   ==> 🆑")
	AllSequences.AddSequence([]rune{0x1f191, 0xfe0e}, "Basic_Emoji                   ==> 🆑")
	AllSequences.AddSequence([]rune{0x1f19a}, "Basic_Emoji                   ==> 🆚")
	AllSequences.AddSequence([]rune{0x1f19a, 0xfe0e}, "Basic_Emoji                   ==> 🆚")

有很多符号都匹配不了，比如 🎵 这个

**Comment by Andrew-M-C** [comment]
非常感谢指出！！已修正，您可以验证一下哈。
这个文件是在 tool/const 下的工具生成的，而工具里面有一段愚蠢的逻辑错误。
