### ISSUE TITLE
[兼容性问题] 旧版本红心无法被识别

### ISSUE THREAD

**Issue by Kolo7** [Andrew-M-C/go.emoji#3]
### 问题表现：

红心表情有两个，❤️[表情符号]和❤[文字符号]
文字符号版本在当前库版本下无非被正确识别替换。

### 研究进展

其原因我有研究是因为红心在 emoji 诞生前就存在于 unicode 编码中，老的编码短的那个

0x2764 ❤

老的在新版本还有个编码

0x2764 0xFE0E ❤

新版本的编码是这样：

0x2764 0xFE0F ❤️

我还找到了 unicode 编码官网，它的emoji-sequences.txt同样只有新的编码，在旧版本中存在0x2764老编码。
https://www.unicode.org/Public/emoji/15.1/emoji-sequences.txt

但我没研究明白，如何让这个库兼容旧的红心❤识别。

### 附上对这个问题的讨论

https://stackoverflow.com/questions/42679712/why-does-the-red-heart-emoji-require-two-code-points-but-the-other-colored-hear

还有对两个两种红心编码的文字定义介绍:

https://www.emojiall.com/zh-hans/code/2764

期待这个库能够提供兼容的方案

**Comment by Kolo7** [comment]
为了临时解决这个问题，我找到了一个正则表达式，它可以替换 Emoji 14.0 版本，一共4702个表情。想必有些新的表情它没有涵盖，但这比起常见的红心无法被识别要让人可接受。

这是问答原文：

https://stackoverflow.com/questions/39575798/how-to-replace-emoji-characters-in-string-using-regex-in-golang

**Comment by Andrew-M-C** [comment]
Good issue! 这个需求是否急迫呢？如果急迫的话我推荐您先 fork 一下处理。
不紧急的话，我研究研究。我的这个 package 跟其他的 emoji 包逻辑不太一样，不是使用正则来识别 emoji 的。要扩展旧版 emoji 的话，针对我这个 package 的模式最合适的是将旧版的 emoji 字符也全部导入

**Comment by Andrew-M-C** [comment]
@Kolo7 本 package 与最新的 emoji 包保持同步，当前就是 15.1 版。请问您是否能找到这个旧版的红心在emoji 的哪一个版本有出现过吗？

**Comment by Andrew-M-C** [comment]
我这个包的逻辑是：导入官方的所有 emoji 包，然后简单的深度优先搜索，找到最长匹配的那一个组合，视为一个 emoji

**Comment by Andrew-M-C** [comment]
@Kolo7 

我研究了一下，本质上是因为从 emoji 13.0 开始，取消了老版本的 emoji，更换成了彩色版。

你可以试一下我正在开发中的 [v1.1.1](https://github.com/Andrew-M-C/go.emoji/tree/feature/v1.1.1) 版，我把 12.1 的 emoji-data.txt 文件也导入了，其中就包含了你提到的这一批 emoji。

麻烦确认下？

**Comment by Andrew-M-C** [comment]
另外，0x2764 0xFE0E 这个编码，看标准应该是不存在的～～0x2764 0xFE0F 就是标准的

**Comment by Andrew-M-C** [comment]
Fixed in v1.1.1

**Comment by Kolo7** [comment]
非常非常感谢，最近一直没关注这个问题，我会近期内查看的

**Comment by Kolo7** [comment]
测过v1.1.1版本了，完美解决这个问题，非常感谢付出

这是我的测试代码
```golang
oldEmoji := "❤♥️"
	i := 0
	fmt.Println(emoji.ReplaceAllEmojiFunc(oldEmoji, func(emoji string) string {
		i++
		fmt.Printf("%02d - %s - UTF-8 len %d\n", i, emoji, len(emoji))
		return fmt.Sprintf("%d-", i)
	}))
```

v1.1.0版本的输出
> 01 - ♥️ - UTF-8 len 6
> ❤1-

v1.1.1版本的输出
> 00 - ❤ - UTF-8 len 3
> 00 - ♥️ - UTF-8 len 6
> 0-0-
