### ISSUE TITLE
Emoji Iteration Incorrectly Identifies Numbers as Emojis

### ISSUE THREAD

**Issue by wyuhuang** [Andrew-M-C/go.emoji#4]
func ExampleIterateChars() {
	s := "China_1m"

	for it := emoji.IterateChars(s); it.Next(); {
		fmt.Println(it.Current(), "-", it.CurrentIsEmoji())
	}

	// Output:
	// C - false
	// h - false
	// i - false
	// n - false
	// a - false
	// _ - false
	// 1 - true -- is error
	// m - false
}

**Comment by Andrew-M-C** [comment]
Please try branch `feature/v1.1.3`, it fixed.
I will release v1.1.3 later
